# Generated by Django 3.0.2 on 2020-01-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='charts',
        ),
    ]
