# Generated by Django 3.0.2 on 2020-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('charts', '0002_remove_song_charts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='songs',
            field=models.ManyToManyField(related_name='songs', to='songs.Song'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
