# Generated by Django 3.0.2 on 2020-01-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20200113_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
