# Generated by Django 3.0.2 on 2020-01-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20200113_1509'),
        ('charts', '0005_auto_20200113_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'Feburary'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('songs', models.ManyToManyField(to='songs.Song')),
            ],
            options={
                'verbose_name_plural': 'Monthly Charts',
            },
        ),
        migrations.CreateModel(
            name='WeeklyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('songs', models.ManyToManyField(to='songs.Song')),
            ],
            options={
                'verbose_name_plural': 'Weekly Charts',
            },
        ),
        migrations.CreateModel(
            name='YearlyChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')])),
                ('songs', models.ManyToManyField(to='songs.Song')),
            ],
            options={
                'verbose_name_plural': 'Yearly Charts',
            },
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(choices=[('BB_100', 'Billborad Hot 100'), ('BB_100', 'Billborad Hot 200')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ChartNames',
        ),
        migrations.AlterField(
            model_name='chart',
            name='month',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charts.MonthlyChart'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='week',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charts.WeeklyChart'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='charts.YearlyChart'),
        ),
        migrations.DeleteModel(
            name='Months',
        ),
        migrations.DeleteModel(
            name='Weeks',
        ),
        migrations.DeleteModel(
            name='Years',
        ),
    ]
