# Generated by Django 3.0.2 on 2020-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0002_remove_song_charts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('charts', models.ManyToManyField(related_name='charts', to='charts.Chart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
