# Generated by Django 3.0.2 on 2020-01-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rank',
            field=models.ManyToManyField(related_name='ranks', to='songs.Rank'),
        ),
    ]
