# Generated by Django 3.0.2 on 2020-01-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created',
        ),
        migrations.RemoveField(
            model_name='song',
            name='modified',
        ),
    ]
